# Dependencies
markdown:         kramdown
highlighter:      rouge # changed from `pygments` as github says so

# Permalinks
permalink:        pretty

# Setup
title:            'Shreyas R H'
tagline:          'Senior Software Engineer @Practo'
description:      ''
url:              
baseurl:          ''
paginate:         5
paginate_path:    ''

author:
  name: 'Shreyas'
  email: 'shreyas.rh9@gmail.com'
  github: shreyasrh9
  twitter: 
  linkedin: 
  goodreads: 
  orcid: h
  google_scholar: 
  email_md5: 4a424eaac867c7c43ac960ad6650bfd1
  emailalt_md5: 3a91811708b61787ecd9018c9becc99b
  disqus_shortname: patricksteadman
  google_analytics_id: UA-27104497-1
  google_analytics_url: 
  bio: 
