# Dependencies
markdown:         kramdown
highlighter:      rouge # changed from `pygments` as github says so

# Permalinks
permalink:        pretty

# Setup
title:            'Manoj Raju'
tagline:          'Senior Data Scientist @Practo'
description:      ''
url:              
baseurl:          ''
paginate:         5
paginate_path:    ''

author:
  name: 'Manoj'
  email: 'rmanuuu@gmail.com'
  github: rmanuuu
  twitter: 
  linkedin: manoj-raju-ab074165
  facebook: 
  goodreads: 
  orcid:  
  google_scholar: 
  email_md5: 
  emailalt_md5: 
  disqus_shortname: Manoj
  google_analytics_id: 
  google_analytics_url: 
  bio: 

theme: jekyll-theme-midnight
